FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 4000
EXPOSE 4000

# Run the app using nodemon (use the exec form for CMD)
CMD ["npm", "run", "start"]
